send_message:
  name: Send message
  description: Send a Whatsapp message
  fields:
    clientId:
      name: Client ID
      description: Which instance of whatsapp should the message come from
      required: true
      example: default
    to:
      name: Target User ID
      description: Target User ID
      required: true
      example: 391234567890@s.whatsapp.net
    body:
      name: Message's body
      description: Message's body
      required: true
      advanced: true

set_status:
  name: Set status
  description: Sets the current user's status message
  fields:
    clientId:
      name: Client ID
      description: Which instance of whatsapp should be used
      required: true
      example: default
    status:
      name: New status message
      description: New status message
      required: true
      example: Available

presence_subscribe:
  name: Presence subscribe
  description: Subscribe to user presence update like online, offline, typing, etc... Please first use send infinity presence update service to always appear online.
  fields:
    clientId:
      name: Client ID
      description: Which instance of whatsapp should be used
      required: true
      example: default
    userId:
      name: Target User ID
      description: Target User ID
      required: true
      example: 391234567890@s.whatsapp.net

send_presence_update:
  name: Send presence update
  description: Send presence update like online, offline, typing, etc...
  fields:
    clientId:
      name: Client ID
      description: Which instance of whatsapp should be used
      required: true
      example: default
    type:
      name: Presence type
      description: Presence type
      required: true
      example: composing
      selector:
        select:
          options:
            - "unavailable"
            - "available"
            - "composing"
            - "recording"
            - "paused"
    to:
      name: Target User ID
      description: Target User ID
      required: false
      example: 391234567890@s.whatsapp.net

send_infinity_presence_update:
  name: Send infinity presence update
  description: Send presence update like online, offline, typing, etc... for a long time
  fields:
    clientId:
      name: Client ID
      description: Which instance of whatsapp should be used
      required: true
      example: default
    type:
      name: Presence type
      description: Presence type
      required: true
      example: composing
      selector:
        select:
          options:
            - "unavailable"
            - "available"
            - "composing"
            - "recording"
            - "paused"
    to:
      name: Target User ID
      description: Target User ID
      required: false
      example: 391234567890@s.whatsapp.net

get_group_metadata:
  name: Get group metadata
  description: Get group metadata
  fields:
    groupID:
      name: Client ID
      description: Which instance of whatsapp should the message come from
      required: true
      example: default
    to:
      name: Group ID
      description: Group ID
      required: true
      example: 76767676767676-123456780@g.us
    body:
      name: Message's body
      description: Message's body
      required: true
      advanced: true